/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "config_constants.h"

namespace com { namespace vrv { namespace im { namespace service {

const configConstants g_config_constants;

configConstants::configConstants() {
}

}}}} // namespace

