/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef config_CONSTANTS_H
#define config_CONSTANTS_H

#include "config_types.h"

namespace com { namespace vrv { namespace im { namespace service {

class configConstants {
 public:
  configConstants();

};

extern const configConstants g_config_constants;

}}}} // namespace

#endif
