/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef commonService_CONSTANTS_H
#define commonService_CONSTANTS_H

#include "commonService_types.h"

namespace com { namespace vrv { namespace cems { namespace common { namespace thrift { namespace service {

class commonServiceConstants {
 public:
  commonServiceConstants();

};

extern const commonServiceConstants g_commonService_constants;

}}}}}} // namespace

#endif
