/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "commonService_types.h"

#include <algorithm>

namespace com { namespace vrv { namespace cems { namespace common { namespace thrift { namespace service {

}}}}}} // namespace
