/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vrv_CONSTANTS_H
#define vrv_CONSTANTS_H

#include "vrv_types.h"



class vrvConstants {
 public:
  vrvConstants();

};

extern const vrvConstants g_vrv_constants;



#endif
