/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bean_CONSTANTS_H
#define bean_CONSTANTS_H

#include "bean_types.h"

namespace com { namespace vrv { namespace cems { namespace service { namespace base { namespace bean { namespace cache {

class beanConstants {
 public:
  beanConstants();

};

extern const beanConstants g_bean_constants;

}}}}}}} // namespace

#endif
