/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bean_constants.h"

namespace com { namespace vrv { namespace cems { namespace service { namespace base { namespace bean { namespace cache {

const beanConstants g_bean_constants;

beanConstants::beanConstants() {
}

}}}}}}} // namespace

