/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cacheService_constants.h"

namespace com { namespace vrv { namespace cems { namespace service { namespace base { namespace interfaces {

const cacheServiceConstants g_cacheService_constants;

cacheServiceConstants::cacheServiceConstants() {
}

}}}}}} // namespace

