/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cacheService_types.h"

#include <algorithm>

namespace com { namespace vrv { namespace cems { namespace service { namespace base { namespace interfaces {

}}}}}} // namespace
