/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cacheService_CONSTANTS_H
#define cacheService_CONSTANTS_H

#include "cacheService_types.h"

namespace com { namespace vrv { namespace cems { namespace service { namespace base { namespace interfaces {

class cacheServiceConstants {
 public:
  cacheServiceConstants();

};

extern const cacheServiceConstants g_cacheService_constants;

}}}}}} // namespace

#endif
