/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "commonService_constants.h"

namespace com { namespace vrv { namespace cems { namespace common { namespace thrift { namespace service {

const commonServiceConstants g_commonService_constants;

commonServiceConstants::commonServiceConstants() {
}

}}}}}} // namespace

