/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vrv_constants.h"



const vrvConstants g_vrv_constants;

vrvConstants::vrvConstants() {
}



